In [26]:
from PIL import Image, ImageDraw, ImageFont
from reportlab.pdfgen import canvas

def image_2_pdf(image_path, output_pdf_path, text):
    # Open the JPEG image
    image = Image.open(image_path)

    # Create a drawing object
    draw = ImageDraw.Draw(image)
  
    font_color = (0, 0, 255)  # white color
    myFont = ImageFont.truetype('FreeMono.ttf', 80)
    # Add text to the image
    draw.text((1000, 80), text, font= myFont, fill=font_color)
    # Save the modified image
    image.save('/gpfs/data1/vclgp/xiongl/ProjectIS2CalVal/result/is2_calval_metrics/tmp.jpeg')
    # Create a PDF file
    pdf = canvas.Canvas(output_pdf_path)
    # Set the PDF dimensions based on the image size
    pdf.setPageSize((image.width, image.height))

    # Draw the image on the PDF
    pdf.drawInlineImage('/gpfs/data1/vclgp/xiongl/ProjectIS2CalVal/result/is2_calval_metrics/tmp.jpeg', 0, 0, width=image.width, height=image.height)

    # Save the PDF
    pdf.save()

In [18]:
import glob
import os

In [27]:
if __name__ == "__main__":
    # Specify the input JPEG file, output image file, output PDF file, and text to be added
    images = glob.glob('/gpfs/data1/vclgp/xiongl/ProjectIS2CalVal/result/is2_calval_metrics/*.jpeg')
    for image in images:
        output_pdf_path = image[:-4] + 'pdf'
        text_to_add = os.path.basename(image)[:-5]
        image_2_pdf(image, output_pdf_path, text_to_add)
        #print(f"Conversion complete. PDF saved to {output_pdf_path}")

In [1]:
VALID_SITES = ['amani','csir_agincourt', 'csir_dnyala', 'csir_ireagh', 'csir_justicia', 'csir_venetia', 'csir_welverdient', 'drc_ghent_field_32635', 
               'drc_ghent_field_32733', 'drc_ghent_field_32734', 'gsfc_mozambique', 'jpl_lope', 'jpl_rabi', 'tanzania_wwf_germany', 'khaoyai_thailand', 
               'chowilla', 'credo', 'karawatha', 'litchfield', 'rushworth_forests', 'tern_alice_mulga', 'tern_robson_whole', 'costarica_laselva2019', 
               'skidmore_bayerischer', 'zofin_180607', 'spain_exts1', 'spain_exts2', 'spain_exts3', 'spain_exts4', 'spain_leonposada', 'spain_leon1', 
               'spain_leon2', 'spain_leon3', 'jpl_borneo_004', 'jpl_borneo_013', 'jpl_borneo_040', 'jpl_borneo_119', 'jpl_borneo_144', 'chave_paracou', 
               'embrapa_brazil_2020_and_a01', 'embrapa_brazil_2020_bon_a01', 'embrapa_brazil_2020_cau_a01', 'embrapa_brazil_2020_duc_a01', 
               'embrapa_brazil_2020_hum_a01', 'embrapa_brazil_2020_par_a01', 'embrapa_brazil_2020_rib_a01', 'embrapa_brazil_2020_tal_a01',
               'embrapa_brazil_2020_tan_a01', 'embrapa_brazil_2020_tap_a01', 'embrapa_brazil_2020_tap_a04', 'walkerfire_20191007', 
               'neon_abby2018', 'neon_abby2019', 'neon_abby2021', 'neon_bart2018', 'neon_bart2019', 'neon_blan2019', 'neon_blan2021', 
               'neon_clbj2018', 'neon_clbj2019', 'neon_clbj2021', 'neon_clbj2021', 'neon_dela2018', 'neon_dela2019', 'neon_dela2021', 
               'neon_dsny2018', 'neon_dsny2021', 'neon_grsm2018', 'neon_grsm2021', 'neon_guan2018', 'neon_harv2018', 'neon_harv2019', 
               'neon_jerc2019', 'neon_jerc2021', 'neon_jorn2018', 'neon_jorn2019', 'neon_jorn2021', 'neon_konz2019', 'neon_konz2020', 
               'neon_leno2018', 'neon_leno2019', 'neon_leno2021', 'neon_mlbs2018', 'neon_mlbs2021', 'neon_moab2018', 'neon_moab2021', 
               'neon_niwo2019', 'neon_niwo2020', 'neon_nogp2021', 'neon_onaq2019', 'neon_onaq2021', 'neon_osbs2018', 'neon_osbs2019', 
               'neon_osbs2021', 'neon_puum2020', 'neon_rmnp2018', 'neon_rmnp2020', 'neon_scbi2019', 'neon_scbi2021', 'neon_serc2019', 
               'neon_serc2021', 'neon_sjer2019', 'neon_soap2018', 'neon_soap2019', 'neon_soap2021', 'neon_srer2019', 'neon_srer2021', 
               'neon_stei2019', 'neon_stei2020', 'neon_ster2021', 'neon_tall2018', 'neon_tall2019', 'neon_tall2021', 'neon_teak2021', 
               'neon_ukfs2018', 'neon_ukfs2019', 'neon_ukfs2020', 'neon_unde2019', 'neon_unde2020', 'neon_wood2021', 'neon_wref2019', 
               'neon_wref2021', 'neon_yell2018', 'neon_yell2019', 'neon_yell2020', 
               'neon_blan2022', 'neon_clbj2022', 'neon_grsm2022', 'neon_moab2022', 'neon_onaq2022', 'neon_rmnp2022', 'neon_serc2022', 
               'neon_stei2022', 'neon_steicheq2022', 'neon_ster2022', 'neon_unde2022', 'inpe_brazil31983', 'inpe_brazil31981', 
               'inpe_brazil31979', 'inpe_brazil31976', 'inpe_brazil31975', 'inpe_brazil31973', 'inpe_brazil31974', 'inpe_brazil31978']
len(VALID_SITES)

144

In [6]:
# get result list 
import os
folder_path = '/gpfs/data1/vclgp/xiongl/ProjectIS2CalVal/result/is2_calval_metrics'
jpeg_files = [f for f in os.listdir(folder_path) if f.lower().endswith('.jpg') or f.lower().endswith('.jpeg')]
jpeg_files [1][:-5]

'africa_drc_ghent_field_32733'

In [7]:
res = []
for site in VALID_SITES:
    flag_done = 0
    for f in jpeg_files:
        if site in f:
            flag_done = 1
            break
    if flag_done == 0:
        res.append(site)

In [9]:
print(res)

['amani', 'gsfc_mozambique', 'jpl_lope', 'tanzania_wwf_germany', 'khaoyai_thailand', 'zofin_180607', 'spain_exts1', 'spain_exts2', 'spain_exts3', 'spain_leon1', 'spain_leon2', 'embrapa_brazil_2020_and_a01', 'neon_bart2018', 'neon_bart2019', 'neon_blan2019', 'neon_blan2021', 'neon_scbi2019', 'neon_scbi2021', 'neon_unde2019', 'neon_blan2022', 'neon_clbj2022', 'neon_grsm2022', 'neon_moab2022', 'neon_onaq2022', 'neon_rmnp2022', 'neon_serc2022', 'neon_stei2022', 'neon_steicheq2022', 'neon_ster2022', 'neon_unde2022', 'inpe_brazil31983', 'inpe_brazil31981', 'inpe_brazil31979', 'inpe_brazil31976', 'inpe_brazil31975', 'inpe_brazil31973', 'inpe_brazil31974', 'inpe_brazil31978']


In [11]:
# check if in projected als sites 

folder_path = '/gpfs/data1/vclgp/xiongl/ProjectIS2CalVal/result/is2_projected_als'
is2_project_files = [f for f in os.listdir(folder_path) ]

In [13]:
for site in res:
    flag_have = 0
    for f in is2_project_files:
        if site in f:
            print(f)
            flag_have = 1
            break
    if flag_have == 0:
        print(site)

africa_amani.parquet
africa_gsfc_mozambique.parquet
africa_jpl_lope.parquet
africa_tanzania_wwf_germany.parquet
asia_khaoyai_thailand.parquet
europe_zofin_180607.parquet
europe_spain_exts1.parquet
europe_spain_exts2.parquet
europe_spain_exts3.parquet
europe_spain_leon1.parquet
europe_spain_leon2.parquet
southamerica_embrapa_brazil_2020_and_a01.parquet
usa_neon_bart2018.parquet
usa_neon_bart2019.parquet
usa_neon_blan2019.parquet
usa_neon_blan2021.parquet
usa_neon_scbi2019.parquet
usa_neon_scbi2021.parquet
usa_neon_unde2019.parquet
usa_neon_blan2022.parquet
usa_neon_clbj2022.parquet
usa_neon_grsm2022.parquet
usa_neon_moab2022.parquet
usa_neon_onaq2022.parquet
usa_neon_rmnp2022.parquet
usa_neon_serc2022.parquet
usa_neon_stei2022.parquet
usa_neon_steicheq2022.parquet
usa_neon_ster2022.parquet
usa_neon_unde2022.parquet
southamerica_inpe_brazil31983.parquet
southamerica_inpe_brazil31981.parquet
southamerica_inpe_brazil31979.parquet
southamerica_inpe_brazil31976.parquet
southamerica_inpe_braz

In [14]:
# check als extraction result 
# yes, it is right

In [15]:
# check als metrics 
import glob
files = glob.glob('/gpfs/data1/vclgp/xiongl/ProjectIS2CalVal/result_als_stat/*.parquet')

In [16]:
import pandas as pd
df = pd.read_parquet(files[1000])

In [18]:
df.columns.values

array(['als_rh0', 'als_rh1', 'als_rh2', 'als_rh3', 'als_rh4', 'als_rh5',
       'als_rh6', 'als_rh7', 'als_rh8', 'als_rh9', 'als_rh10', 'als_rh11',
       'als_rh12', 'als_rh13', 'als_rh14', 'als_rh15', 'als_rh16',
       'als_rh17', 'als_rh18', 'als_rh19', 'als_rh20', 'als_rh21',
       'als_rh22', 'als_rh23', 'als_rh24', 'als_rh25', 'als_rh26',
       'als_rh27', 'als_rh28', 'als_rh29', 'als_rh30', 'als_rh31',
       'als_rh32', 'als_rh33', 'als_rh34', 'als_rh35', 'als_rh36',
       'als_rh37', 'als_rh38', 'als_rh39', 'als_rh40', 'als_rh41',
       'als_rh42', 'als_rh43', 'als_rh44', 'als_rh45', 'als_rh46',
       'als_rh47', 'als_rh48', 'als_rh49', 'als_rh50', 'als_rh51',
       'als_rh52', 'als_rh53', 'als_rh54', 'als_rh55', 'als_rh56',
       'als_rh57', 'als_rh58', 'als_rh59', 'als_rh60', 'als_rh61',
       'als_rh62', 'als_rh63', 'als_rh64', 'als_rh65', 'als_rh66',
       'als_rh67', 'als_rh68', 'als_rh69', 'als_rh70', 'als_rh71',
       'als_rh72', 'als_rh73', 'als_rh74', 'als_

In [1]:
# test index 
import pandas as pd
sites =pd.read_parquet('../data/all_sites_20231218.parquet')

In [3]:
todo=['amani', 'gsfc_mozambique', 'jpl_lope', 
      'tanzania_wwf_germany', 'khaoyai_thailand', 
      'zofin_180607', 'spain_exts1', 'spain_exts2', 'spain_exts3', 
      'spain_leon1', 'spain_leon2', 'embrapa_brazil_2020_and_a01', 
      'neon_bart2018', 'neon_bart2019', 'neon_blan2019', 'neon_blan2021', 
      'neon_scbi2019', 'neon_scbi2021', 'neon_unde2019', 'neon_blan2022', 
      'neon_clbj2022', 'neon_grsm2022', 'neon_moab2022', 'neon_onaq2022', 
      'neon_rmnp2022', 'neon_serc2022', 'neon_stei2022', 'neon_steicheq2022',
      'neon_ster2022', 'neon_unde2022', 'inpe_brazil31983', 'inpe_brazil31981',
      'inpe_brazil31979', 'inpe_brazil31976', 'inpe_brazil31975', 
      'inpe_brazil31973', 'inpe_brazil31974', 'inpe_brazil31978']

In [11]:
import PyPDF2
def merge_pdfs(filepaths, output_filepath):
    # Create a PDF merger object
    pdf_merger = PyPDF2.PdfMerger()

    # Iterate through each PDF file and append it to the merger
    for filepath in filepaths:
        with open(filepath, 'rb') as pdf_file:
            pdf_merger.append(pdf_file)

    # Write the merged PDF to the output file
    with open(output_filepath, 'wb') as output_file:
        pdf_merger.write(output_file)

In [12]:
import glob
pdf_files_to_merge = glob.glob('/gpfs/data1/vclgp/xiongl/ProjectIS2CalVal/result/is2_calval_metrics/*.pdf')

# Output file name for the merged PDF
output_pdf_file = 'merged_output.pdf'

# Call the merge_pdfs function
merge_pdfs(pdf_files_to_merge, output_pdf_file)

In [13]:
import numpy as np
np.searchsorted([1,2,3,4,5], [4,5,6,7,8,9], side='left')

array([3, 4, 5, 5, 5, 5])

In [11]:
import numpy as np

# Example arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 5, 6, 7])

# Find the common elements
common_elements = np.intersect1d(array1, array2)

# Display the common elements
print(common_elements)
import numpy as np

# Check if each element of array1 is in common
is_in_array1 = np.in1d(array1, common_elements)

# Display the result
print(is_in_array1)
array1[is_in_array1]


[3 4 5]
[False False  True  True  True]


array([3, 4, 5])